export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER";

export const GET_ALL_STAFFS = "GET_ALL_STAFFS";
export const GET_STAFF_DETAILS = "GET_STAFF_DETAILS";

export const GET_TOTAL_PROJECTS = "GET_TOTAL_PROJECTS";
export const GET_NEW_PROJECTS = "GET_NEW_PROJECTS";
export const GET_LATEST_PROJECTS = "GET_LATEST_PROJECTS";
export const GET_ACTIVE_PROJECTS = "GET_ACTIVE_PROJECTS";
export const GET_MILESTONES_BY_PROJECT_ID = "GET_MILESTONES_BY_PROJECT_ID";

export const GET_TOTAL_USERS = "GET_TOTAL_USERS";
export const GET_NEW_USERS = "GET_NEW_USERS";
export const GET_LATEST_USERS = "GET_LATEST_USERS";
export const GET_ACTIVE_USERS = "GET_ACTIVE_USERS";
export const GET_INACTIVE_USERS = "GET_INACTIVE_USERS";
export const GET_RETENTION_RATE = "GET_RETENTION_RATE";
export const GET_PROJECTS_BY_USER_ID = "GET_PROJECTS_BY_USER_ID";

export const GET_TOTAL_MILESTONES = "GET_TOTAL_MILESTONES";
export const GET_COMPLETED_MILESTONES = "GET_COMPLETED_MILESTONES";
export const GET_AVERAGE_MILESTONES_PER_PROJECT = "GET_AVERAGE_MILESTONES_PER_PROJECT";
export const GET_AVERAGE_TASKS_PER_MILESTONE = "GET_AVERAGE_TASKS_PER_MILESTONE";
export const GET_MILESTONES_COMPLETION_DATA = "GET_MILESTONES_COMPLETION_DATA";
export const GET_MILESTONES_DEADLINES_MISSED_RATE = "GET_MILESTONES_DEADLINES_MISSED_RATE";
export const GET_MILESTONES_FEATURE_UTILIZATION_RATE = "GET_MILESTONES_FEATURE_UTILIZATION_RATE";

export const GET_TOTAL_TASKS = "GET_TOTAL_TASKS";
export const GET_PENDING_TASKS = "GET_PENDING_TASKS";
export const GET_COMPLETED_TASKS = "GET_COMPLETED_TASKS";
export const GET_TASKS_COMPLETION_DATA = "GET_TASKS_COMPLETION_DATA";
export const GET_TASKS_FEATURE_UTILIZATION_RATE = "GET_TASKS_FEATURE_UTILIZATION_RATE";

export const GET_TOTAL_MESSAGES = "GET_TOTAL_MESSAGES";

export const SET_RECENCY_DAYS = "SET_RECENCY_DAYS";

export const SET_LOADING = "SET_LOADING";

export const GET_PROJECT_NAME = "GET_PROJECT_NAME";
export const GET_PROJECT_MILESTONES_COUNT = "GET_PROJECT_MILESTONES_COUNT";
export const GET_PROJECT_COMPLETED_TASKS_COUNT = "GET_PROJECT_COMPLETED_TASKS_COUNT";
export const GET_PROJECT_INCOMPLETE_TASKS_COUNT = "GET_PROJECT_INCOMPLETE_TASKS_COUNT";
export const GET_PROJECT_MESSAGES_COUNT = "GET_PROJECT_MESSAGES_COUNT";
export const GET_PROJECT_COMMITS_COUNT = "GET_PROJECT_COMMITS_COUNT";
export const GET_PROJECT_FILE_CHANGES_COUNT = "GET_PROJECT_FILE_CHANGES_COUNT";
export const GET_MEMBERS_INFO = "GET_MEMBERS_INFO";
export const GET_PROJECT_GITHUB_REPO = "GET_PROJECT_GITHUB_REPO";
export const GET_PROJECT_ACTIVITIES = "GET_PROJECT_ACTIVITIES";
export const GET_PROJECT_DRIVE_LINK = "GET_PROJECT_DRIVE_LINK";
export const GET_PROJECT_MILESTONES = "GET_PROJECT_MILESTONES";
export const GET_PROJECT_TASKS_CONTRIBUTION = "GET_PROJECT_TASKS_CONTRIBUTION";
export const GET_PROJECT_GITHUB_ADDITIONS_COUNT = "GET_PROJECT_GITHUB_ADDITIONS_COUNT";
export const GET_PROJECT_GITHUB_DELETIONS_COUNT = "GET_PROJECT_GITHUB_DELETIONS_COUNT";
export const GET_PROJECT_GITHUB_COMMITS = "GET_PROJECT_GITHUB_COMMITS";
export const GET_PROJECT_GITHUB_COMMITS_CONTRIBUTION = "GET_PROJECT_GITHUB_COMMITS_CONTRIBUTION";
export const GET_PROJECT_GITHUB_LOCS_CONTRIBUTION = "GET_PROJECT_GITHUB_LOCS_CONTRIBUTION";
export const GET_PROJECT_FILES_COUNT = "GET_PROJECT_FILES_COUNT";
export const GET_PROJECT_FILES_CHANGES = "GET_PROJECT_FILES_CHANGES";
export const GET_PROJECT_FILES_CONTRIBUTIONS = "GET_PROJECT_FILES_CONTRIBUTIONS";

export const GET_USER_NAME = "GET_USER_NAME";
export const GET_USER_PROJECTS_COUNT = "GET_USER_PROJECTS_COUNT";
export const GET_USER_COMPLETED_TASKS_COUNT = "GET_USER_COMPLETED_TASKS_COUNT";
export const GET_USER_INCOMPLETE_TASKS_COUNT = "GET_USER_INCOMPLETE_TASKS_COUNT";
export const GET_USER_MESSAGES_COUNT = "GET_USER_MESSAGES_COUNT";
export const GET_USER_COMMITS_COUNT = "GET_USER_COMMITS_COUNT";
export const GET_USER_FILE_CHANGES_COUNT = "GET_USER_FILE_CHANGES_COUNT";
export const GET_PROJECTS_INFO = "GET_PROJECTS_INFO";
export const GET_USER_ACTIVITIES = "GET_USER_ACTIVITIES";
export const GET_USER_GITHUB_ACCOUNT = "GET_USER_GITHUB_ACCOUNT";
export const GET_USER_EMAIL = "GET_USER_EMAIL";
export const GET_USER_PROJECTS_TASKS = "GET_USER_PROJECTS_TASKS";
export const GET_USER_TASKS_CONTRIBUTION = "GET_USER_TASKS_CONTRIBUTION";
export const GET_USER_GITHUB_ADDITIONS = "GET_USER_GITHUB_ADDITIONS";
export const GET_USER_GITHUB_DELETIONS = "GET_USER_GITHUB_DELETIONS";
export const GET_USER_COMMITS = "GET_USER_COMMITS";
export const GET_USER_COMMITS_CONTRIBUTION = "GET_USER_COMMITS_CONTRIBUTION";
export const GET_USER_LOCS_CONTRIBUTION = "GET_USER_LOCS_CONTRIBUTION";
export const GET_USER_FILES_COUNT = "GET_USER_FILES_COUNT";
export const GET_USER_FILES_CHANGES = "GET_USER_FILES_CHANGES";
export const GET_USER_FILES_CONTRIBUTION = "GET_USER_FILES_CONTRIBUTION";
