export const CHANGE_CONTENT_TYPE = 'CHANGE_CONTENT_TYPE';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER';

export const  GET_ALL_STAFFS = 'GET_ALL_STAFFS';
export const GET_STAFF_DETAILS = 'GET_STAFF_DETAILS';

export const GET_TOTAL_PROJECTS = 'GET_TOTAL_PROJECTS';
export const GET_NEW_PROJECTS = 'GET_NEW_PROJECTS';
export const GET_LATEST_PROJECTS = 'GET_LATEST_PROJECTS';
export const GET_ACTIVE_PROJECTS = 'GET_ACTIVE_PROJECTS';
export const GET_MILESTONES_BY_PROJECT_ID = 'GET_MILESTONES_BY_PROJECT_ID';

export const GET_TOTAL_USERS = 'GET_TOTAL_USERS';
export const GET_NEW_USERS = 'GET_NEW_USERS';
export const GET_LATEST_USERS = 'GET_LATEST_USERS';
export const GET_ACTIVE_USERS = 'GET_ACTIVE_USERS';
export const GET_INACTIVE_USERS = 'GET_INACTIVE_USERS';
export const GET_RETENTION_RATE = 'GET_RETENTION_RATE';
export const GET_PROJECTS_BY_USER_ID = 'GET_PROJECTS_BY_USER_ID';

export const GET_TOTAL_MILESTONES = 'GET_TOTAL_MILESTONES';
export const GET_COMPLETED_MILESTONES = 'GET_COMPLETED_MILESTONES';
export const GET_AVERAGE_MILESTONES_PER_PROJECT = 'GET_AVERAGE_MILESTONES_PER_PROJECT';
export const GET_AVERAGE_TASKS_PER_MILESTONE = 'GET_AVERAGE_TASKS_PER_MILESTONE';
export const GET_MILESTONES_COMPLETION_DATA = 'GET_MILESTONES_COMPLETION_DATA';
export const GET_MILESTONES_DEADLINES_MISSED_RATE = 'GET_MILESTONES_DEADLINES_MISSED_RATE';
export const GET_MILESTONES_FEATURE_UTILIZATION_RATE = 'GET_MILESTONES_FEATURE_UTILIZATION_RATE';

export const GET_TOTAL_TASKS = 'GET_TOTAL_TASKS';
export const GET_PENDING_TASKS = 'GET_PENDING_TASKS';
export const GET_COMPLETED_TASKS = 'GET_COMPLETED_TASKS';
export const GET_TASKS_COMPLETION_DATA = 'GET_TASKS_COMPLETION_DATA';
export const GET_TASKS_FEATURE_UTILIZATION_RATE = 'GET_TASKS_FEATURE_UTILIZATION_RATE';

export const GET_TOTAL_MESSAGES = 'GET_TOTAL_MESSAGES';
